name = "pygamer_usb_gamepad"
description = "Turn your PyGamer into a USB gamepad"
version = "1.0.0"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["pygamer_usb_controller"]

[[depends-on]]
pygamer_bsp = "^1.0.0"

[[pins]]
pygamer_bsp = { url='https://github.com/Fabien-Chouteau/pygamer-bsp' }
